import Foundation

/// A grid cell in a maze, identified by integer column/row coordinates.
public struct MazeCell: Hashable {
    public var x: Int
    public var y: Int
    public init(x: Int, y: Int) {
        self.x = x
        self.y = y
    }
}

/// An unordered passage (a removed wall) between two adjacent cells. Stored
/// normalized (lexicographically smaller cell first) so `(a,b) == (b,a)` — the
/// pair hashes and compares independently of the order it was carved.
public struct Passage: Hashable {
    public let a: MazeCell
    public let b: MazeCell

    public init(_ p: MazeCell, _ q: MazeCell) {
        // Normalize ordering so the passage is direction-independent.
        if (p.x, p.y) <= (q.x, q.y) {
            self.a = p
            self.b = q
        } else {
            self.a = q
            self.b = p
        }
    }
}

/// A small deterministic linear-congruential PRNG so maze generation is
/// reproducible per seed (unlike `SystemRandomNumberGenerator`).
private struct LCG {
    var state: UInt64
    init(seed: Int) {
        // Avoid a zero state; mix the seed a little.
        state = UInt64(bitPattern: Int64(seed)) &* 0x9E3779B97F4A7C15 &+ 0x1234_5678_9ABC_DEF
        if state == 0 { state = 0xDEAD_BEEF }
    }
    mutating func next() -> UInt64 {
        state = state &* 6364136223846793005 &+ 1442695040888963407
        return state
    }
    /// Uniform integer in 0..<n.
    mutating func int(_ n: Int) -> Int {
        precondition(n > 0)
        return Int(next() >> 11) % n
    }
}

/// A perfect maze (spanning tree of corridors) over a `cols × rows` grid,
/// generated by the recursive-backtracker algorithm with a seeded PRNG.
public struct Maze {
    public let cols: Int
    public let rows: Int
    public let passages: Set<Passage>     // carved edges; a perfect maze has cols*rows-1
    public let carveOrder: [Passage]      // passages in the order carved (for animation)

    public init(cols: Int, rows: Int, passages: Set<Passage>, carveOrder: [Passage]) {
        self.cols = cols
        self.rows = rows
        self.passages = passages
        self.carveOrder = carveOrder
    }

    /// Recursive-backtracker perfect maze from a SEEDED PRNG (deterministic per seed).
    public static func generate(cols: Int, rows: Int, seed: Int) -> Maze {
        precondition(cols > 0 && rows > 0)
        var rng = LCG(seed: seed)
        var visited = [Bool](repeating: false, count: cols * rows)
        func idx(_ x: Int, _ y: Int) -> Int { y * cols + x }

        var passages = Set<Passage>()
        var carveOrder: [Passage] = []

        var stack: [MazeCell] = [MazeCell(x: 0, y: 0)]
        visited[idx(0, 0)] = true

        let neighborOffsets = [(1, 0), (-1, 0), (0, 1), (0, -1)]

        while let current = stack.last {
            // Collect unvisited orthogonal neighbors.
            var candidates: [MazeCell] = []
            for (dx, dy) in neighborOffsets {
                let nx = current.x + dx
                let ny = current.y + dy
                if nx >= 0, nx < cols, ny >= 0, ny < rows, !visited[idx(nx, ny)] {
                    candidates.append(MazeCell(x: nx, y: ny))
                }
            }
            if candidates.isEmpty {
                stack.removeLast()
                continue
            }
            let next = candidates[rng.int(candidates.count)]
            visited[idx(next.x, next.y)] = true
            let passage = Passage(current, next)
            passages.insert(passage)
            carveOrder.append(passage)
            stack.append(next)
        }

        return Maze(cols: cols, rows: rows, passages: passages, carveOrder: carveOrder)
    }

    /// True if a carved passage directly connects two (adjacent) cells.
    public func connected(_ a: MazeCell, _ b: MazeCell) -> Bool {
        passages.contains(Passage(a, b))
    }

    /// Adjacency list of cells reachable from `cell` through carved passages.
    private func neighbors(of cell: MazeCell) -> [MazeCell] {
        var result: [MazeCell] = []
        for (dx, dy) in [(1, 0), (-1, 0), (0, 1), (0, -1)] {
            let n = MazeCell(x: cell.x + dx, y: cell.y + dy)
            guard n.x >= 0, n.x < cols, n.y >= 0, n.y < rows else { continue }
            if passages.contains(Passage(cell, n)) { result.append(n) }
        }
        return result
    }

    /// True if every cell is reachable from (0,0) through passages (BFS).
    public func isFullyConnected() -> Bool {
        guard cols > 0, rows > 0 else { return true }
        var seen = Set<MazeCell>()
        var queue = [MazeCell(x: 0, y: 0)]
        seen.insert(MazeCell(x: 0, y: 0))
        var head = 0
        while head < queue.count {
            let cell = queue[head]; head += 1
            for n in neighbors(of: cell) where !seen.contains(n) {
                seen.insert(n)
                queue.append(n)
            }
        }
        return seen.count == cols * rows
    }

    /// Shortest path from (0,0) to (cols-1, rows-1) through passages (BFS). Cells in order.
    public func solve() -> [MazeCell] {
        let start = MazeCell(x: 0, y: 0)
        let goal = MazeCell(x: cols - 1, y: rows - 1)
        var cameFrom = [MazeCell: MazeCell]()
        var seen: Set<MazeCell> = [start]
        var queue = [start]
        var head = 0
        while head < queue.count {
            let cell = queue[head]; head += 1
            if cell == goal { break }
            for n in neighbors(of: cell) where !seen.contains(n) {
                seen.insert(n)
                cameFrom[n] = cell
                queue.append(n)
            }
        }
        guard seen.contains(goal) else { return [] }
        var path = [goal]
        var cur = goal
        while cur != start, let prev = cameFrom[cur] {
            path.append(prev)
            cur = prev
        }
        return path.reversed()
    }
}
